version: '3.3'

services:
  db:
    image: mysqlcompose
    restart: always
    env_file:
      - ./config/db.env
    ports:
      - "3307:3307"
    networks:
      - dockercompose

  backend:
    depends_on:
      - db
    image: flaskcompose
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - /home/guilherme/Projetos/docker/udemy/docker_compose/6_bind_mount_compose/flask:/app
    networks:
      - dockercompose

networks:
  dockercompose: